server:
  port: 8083

spring:
  application:
    name: ticket-stock-service
  threads:
    virtual:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.ticketbooking: INFO

feign:
  sentinel:
    enabled: true

