server:
  port: 9000

spring:
  application:
    name: ticket-gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ticket-user-service
          uri: lb://ticket-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/ticket/**
          filters:
            - StripPrefix=1

        - id: ticket-order-service
          uri: lb://ticket-order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

        - id: ticket-stock-service
          uri: lb://ticket-stock-service
          predicates:
            - Path=/api/stock/**
          filters:
            - StripPrefix=1


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.ticketbooking: INFO
