server:
  port: 8082

spring:
  application:
    name: ticket-order-service
  threads:
    virtual:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.ticketbooking: INFO
