server:
  port: 8081

spring:
  application:
    name: ticket-user-service
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

feign:
  sentinel:
    enabled: true