server:
  port: 8080
  servlet:
    context-path: /ticket

spring:
  application:
    name: ticket-service
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.ticketbooking: INFO

feign:
  sentinel:
    enabled: true